### ISSUE TITLE
Multi project - git.properties got overwritten

### ISSUE THREAD

**Issue by muchino** [ktoso/maven-git-commit-id-plugin#264] opened 2016-11-15 16:15 UTC
I have several "independent" projects. 
The only same part is the shared parent pom, where I configured your cool maven plugin in this way attached below.

my issue is now, that my project depends on a library, where I use the same parent. 
In the first moment of the build the git.properties file is correct, after some seconds it's gotten replaced by the git file from the dependency. 

Any idea why this happens?
Thank you for your help. 

```


<plugin>
					<groupId>pl.project13.maven</groupId>
					<artifactId>git-commit-id-plugin</artifactId>
					<version>2.2.1</version>
					<executions>
						<execution>
							<goals>
								<goal>revision</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<!-- the prefix for the properties -->
						<prefix>git</prefix>
						<!-- that's the default value -->
						<dateFormat>dd.MM.yyyy '@' HH:mm:ss z</dateFormat>
						<!-- true is default here, it prints some more information during the build -->
						<verbose>true</verbose>
						<failOnNoGitDirectory>true</failOnNoGitDirectory>
						<failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>

					
						<!-- 
						read up about git-describe on the in man, or it's homepage - it's a really powerful versioning helper 
						and the recommended way to use git-commit-id-plugin. The configuration bellow is optional, 
						by default describe will run "just like git-describe on the command line", even though it's a JGit reimplementation.
						-->
						<gitDescribe>
							<skip>false</skip>
							<dirty>-SNAPSHOT</dirty>
						</gitDescribe>
		    
						<!-- this is false by default, forces the plugin to generate the git.properties file -->
						<generateGitPropertiesFile>true</generateGitPropertiesFile>
						<!-- 
						The path for the to be generated properties file, it's relative to ${project.basedir} 
						The default value is ${project.build.outputDirectory}/git.properties
						-->
						<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
						<!-- Denotes the format to save properties in. Valid options are "properties" (default) and "json". Properties will be saved to the generateGitPropertiesFilename if generateGitPropertiesFile is set to `true`. -->
						<format>properties</format>
						<skipPoms>true</skipPoms>
						<injectAllReactorProjects>false</injectAllReactorProjects>
					</configuration>
				</plugin>


```

**Comment by TheSnoozer** [comment] 2016-11-22 13:39
can you provide a sample project where we can test this?
That would help a ton for debugging....

**Comment by muchino** [comment] 2016-11-22 17:20
I have to check. The issue with example project: it seems to be a time related issue, because in some repositories there is no issue with the same config and more strange: it depend whos compiling it on which machine. the issue can come and gone :/ 

I will see to find some time for an example project - but it will be hard for me too ;)

**Comment by TheSnoozer** [comment] 2017-01-03 00:14
Any luck to reproduce?

**Comment by TheSnoozer** [comment] 2017-07-18 07:42
Tested this with https://github.com/TheSnoozer/git-commit-id-debugging and couldn't reproduce
Please feel free to open a new ticket with further input on how to reproduce et. al.
~ Closing ~

**Closed by TheSnoozer** 2017-07-18 07:42 UTC
Labels: still open?
