### ISSUE TITLE
Does not work with git worktree

### ISSUE THREAD

**Issue by davireis** [ktoso/maven-git-commit-id-plugin#285] opened 2017-06-09 20:00 UTC
Working directories created with https://git-scm.com/docs/git-worktree unfortunately use a `.git` file whose contents is the path of the real `.git` directory, and that breaks the check maven-git-commit-id does. The only workaround I found was to set `failOnUnableToExtractRepoInfo`. Ideally, maven-git-commit-id should use git itself to verify existence and query data in the `.git` dir.

**Comment by ktoso** [comment] 2017-06-10 05:32
Thanks for the ticket, I'm not actively maintaining this repo so it would be best if you try to submit a PR. I'm happy to review / merge then etc,

**Comment by TheSnoozer** [comment] 2017-06-30 15:57
Not to be picky but this is pretty much a duplicate of
https://github.com/ktoso/maven-git-commit-id-plugin/issues/215

**Closed by TheSnoozer** 2017-06-30 15:57 UTC
Labels: bug
