### ISSUE TITLE
Forces Eclipse to build once per second

### ISSUE THREAD

**Issue by orlade** [ktoso/maven-git-commit-id-plugin#107] opened 2014-05-04 23:04 UTC
I can't figure out if this is as designed or not, but with the plugin listed in pom.xml, Eclipse invokes "Maven Project Builder" once every second, seemingly only to update the timestamp in the git.properties file. I tried adding a `phase` tag to the plugin, but it didn't help. Here's what I'm using:

      
      <plugin>
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>2.1.9</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>revision</goal>
            </goals>
          </execution>
        </executions>

        <configuration>
          <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
          <generateGitPropertiesFile>true</generateGitPropertiesFile>
          <generateGitPropertiesFilename>src/main/resources/git.properties</generateGitPropertiesFilename>
          <failOnNoGitDirectory>true</failOnNoGitDirectory>
        </configuration>
      </plugin>

**Comment by TheSnoozer** [comment] 2015-04-08 22:23
Hi,
the issue https://github.com/ktoso/maven-git-commit-id-plugin/issues/151 seems to be related to this problem.
The issue #151 was resolved with the PR #152

The fix should be included in version 2.1.13.
Can someone do me the favour and check if the problem is still present (I currently can not reproduce it)?


Thanks,

**Comment by nealeu** [comment] 2015-10-14 19:54
I just noticed this and related issues, as we are using this plugin but not having them.

The reason this is happening is that the src/ folder is a watched folder in Eclipse for files that are edited by humans.  The target folder is where all derived resources should go.

Our settings specify:
````
<phase>prepare-package</phase>
````
and
````
<generateGitPropertiesFilename>target/classes/properties/git.properties</generateGitPropertiesFilename>
````
Later phases then package this for deployment

**Comment by TheSnoozer** [comment] 2015-10-14 20:34
@nealeu,
this makes sense.....I just found two articles ([1] and [2]) that support the thesis that eclipse or the "Maven Project Builder" will be invoked when it detects some changes in the project.

quote from [2]
```
Plug-ins contribute incremental project builders to the platform in order to implement specialized resource transformations. For example, the Java development tools (JDT)define an incremental project builder that compiles a Java source file into a class file any time a file is added or modified in a Java project.
```

I'm not sure though if the "Maven Project Builder" is an incremental project builder, but anyhow it sounds like this is by design. Maybe the only thing we could do here is put a warning in the readme...

[1] https://www.eclipse.org/articles/Article-Builders/builders.html
[2] http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2FresAdv_builders.htm

**Comment by TheSnoozer** [comment] 2016-06-08 16:46
I added a note to the readme and based on the discussion I would go ahead and close this issue since there is not much we can do to change the behaviour of internal IDE project builder.

**Closed by TheSnoozer** 2016-06-08 16:46 UTC
Labels: testing
