### ISSUE TITLE
Using git-commit-id-plugin on OpenShift #2

### ISSUE THREAD

**Issue by tavolate** [ktoso/maven-git-commit-id-plugin#201] opened 2015-06-06 10:18 UTC
When I push my commit to OpenShift and it bulids the project automatically, maven fails the build with this error
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
remote: at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1246)
remote: at org.eclipse.jgit.treewalk.FileTreeIterator.(FileTreeIterator.java:88)
remote: at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:126)
remote: at pl.project13.jgit.DescribeCommand.findDirtyState(DescribeCommand.java:362)
remote: at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:298)

I used the solution suggested in https://github.com/ktoso/maven-git-commit-id-plugin/issues/50#issuecomment-109340222 but I still have the problem. Locally everythings works well!

**Comment by TheSnoozer** [comment] 2015-06-07 07:36
Hi @tavolate,
thanks for reporting your issue.
How does you config currently look like?
What version of OpenShift you are using?
Anything bit of information help here.

Thanks,

**Comment by tavolate** [comment] 2015-06-07 19:31
This is my configurati in
<configuration>
    

    
    <generateGitPropertiesFile>true</generateGitPropertiesFile>

    
    <generateGitPropertiesFilename>src/main/resources/git.properties</generateGitPropertiesFilename>
</configuration>

**Comment by TheSnoozer** [comment] 2015-06-07 21:46
What happens if you add
``<dotGitDirectory>path-to-your-git-project</dotGitDirectory>``
to your config?

default is: ${project.basedir}/.git
Is this a valid git-directory on the system where the build fails?

**Comment by tavolate** [comment] 2015-06-08 08:59
With this, I have this exception:

org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
remote: at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1246)
remote: at org.eclipse.jgit.treewalk.FileTreeIterator.(FileTreeIterator.java:88)
remote: at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:126)
remote: at pl.project13.jgit.DescribeCommand.findDirtyState(DescribeCommand.java:362)
remote: at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:298)

**Comment by TheSnoozer** [comment] 2015-06-08 14:09
Can you try as outlined in https://forums.openshift.com/fatal-not-a-git-repository-or-any-of-the-parent-directories-git the following:

```
1) Create an application call foo
NOTE: If you create an app with the rhc client tools (and not the web console), step 2 should be done for you.
2) Do a "git clone foo's_git_URL"
This should create a local directory called "foo" (e.g., appName)
3) cd foo
4) cat .git/config
If you see similar content, then you know you're in a git repository, from which you can run "git add remote..." and not get the error: "fatal: Not a git repository"
```

```config
[core]  
    repositoryformatversion = 0  
    filemode = true  
    bare = false  
    logallrefupdates = true   
    ignorecase = true  
[remote "origin"]  
    fetch = +refs/heads/*:refs/remotes/origin/*  
    url = ssh://b4620defe6fc4f0bab2b24c9838f20ea@foo-macdomain.rhcloud.com/~/git/foo.git/  
[branch "master"]  
    remote = origin  
    merge = refs/heads/master  
```
Add this directory to the git config with ``<dotGitDirectory>path-to-your-git-project</dotGitDirectory>``

**Comment by tavolate** [comment] 2015-06-08 15:07
This is my .git/config local

[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://*********/vilma.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "testing"]
	url =ssh://*********/~/git/vilma.git
	fetch = +refs/heads/*:refs/remotes/testing/*
[remote "production"]
	url = ssh://*********/~/git/vilma.git
	fetch = +refs/heads/*:refs/remotes/production/*

but I think that the problem is the git/config on openshit

[core]
        repositoryformatversion = 0
        filemode = true
        bare = true
        logAllRefUpdates = true
[remote "origin"]
        url = /var/lib/openshift/********/git/template
[pack]
        windowMemory = 200m

**Comment by TheSnoozer** [comment] 2015-06-08 20:55
That's right. The Problem is on the side of the OpenShift.
The OpenShift has currently a so called ``Bare Repository``.
However the maven-git-commit-id-plugin need a ``Working Repository``.
This article summarizes pretty good what the difference between those two are:
http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/

The keypoint is:
``Because no one ever makes edits directly to files in the shared bare repo, a working tree is not needed.`` the maven-git-commit-id-plugin needs a working tree to work :-)

**Comment by tavolate** [comment] 2015-06-08 20:59
Thank you for your time and your work!

**Comment by TheSnoozer** [comment] 2015-06-08 21:03
No worries, the key point is:
You need a way to config your job that it will create a clone the original git repository.
A ``git clone URL-TO-YOUR-REPO`` will create a ``Working Repository``.

E.g.
``git clone git@github.com:ktoso/maven-git-commit-id-plugin.git``
Also if you found a way to do so, please let us know :-)

**Comment by TheSnoozer** [comment] 2015-06-14 18:49
Hi @tavolate,
could you solve your problem?
If yes please let us know how :-)
Thanks

**Comment by TheSnoozer** [comment] 2015-07-10 16:55
Hi @tavolate,
any updates on this issue? otherwise I'll close it.

Thanks,

**Comment by tavolate** [comment] 2015-07-10 17:13
Hi,

no, I didn't find a solution. I don't use your plugin on openshift.

Thanks
Il 10/lug/2015 06:55 PM, "TheSnoozer" <notifications@github.com> ha scritto:

**Comment by TheSnoozer** [comment] 2015-07-10 17:21
Ok, thanks for the feedback.
Will close this issue then.

**Closed by TheSnoozer** 2015-07-10 17:21 UTC
Labels: still open?
