### ISSUE TITLE
release 2.1.13 does not expose git.* properties to the pom

### ISSUE THREAD

**Issue by roytmana** [ktoso/maven-git-commit-id-plugin#176] opened 2015-03-31 03:48 UTC
neither in filtered resources or other places git.* properties are resolved. had to revert to build 2.1.12

**Comment by TheSnoozer** [comment] 2015-04-01 07:38
Hi,
the version 2.1.13 works fine on my side.
Can you post your current configuration?

Thanks,

**Comment by roytmana** [comment] 2015-04-01 14:33
I am running Maven 3.2.5
```
<plugin>
        <!-- https://github.com/ktoso/maven-git-commit-id-plugin -->
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>2.1.13</version>
        <executions>
          <execution>
            <goals>
              <goal>revision</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <dateFormat>yyyy-MM-dd HH:mm:ss z</dateFormat>
          <verbose>true</verbose>
          <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
          <generateGitPropertiesFile>true</generateGitPropertiesFile>
          <generateGitPropertiesFilename>target/classes/version.properties</generateGitPropertiesFilename>
          <failOnNoGitDirectory>false</failOnNoGitDirectory>
          <skip>false</skip>
          <excludeProperties>
            <excludeProperty>git.remote.*</excludeProperty>
          </excludeProperties>
          <abbrevLength>8</abbrevLength>
          <gitDescribe>
            <skip>false</skip>
            <always>false</always>
            <abbrev>8</abbrev>
            <dirty>-dirty</dirty>
            <forceLongFormat>false</forceLongFormat>
          </gitDescribe>
        </configuration>
      </plugin>
```

**Comment by TheSnoozer** [comment] 2015-04-05 14:33
I can reproduce the behavior and I think is intential.
If you add the option to the config it should work fine:

'''
<configuration>
  ...
  <injectAllReactorProjects>true</injectAllReactorProjects>
  ...
</configuration>
'''

**Comment by TheSnoozer** [comment] 2015-04-07 21:44
Hi @roytmana,
I just wanted to check if the suggested configuration option fixed your problem.

Thanks,

**Comment by roytmana** [comment] 2015-04-07 23:00
yes it does thank you but I am wondering if it should not be default as the props do not get exposed even with a simple single module project breaking plugin's backward compatibility

**Comment by TheSnoozer** [comment] 2015-04-08 07:07
Well the problem get's complicated when you have a multi-pom project with different git-projects.

The issue is related to:
https://github.com/ktoso/maven-git-commit-id-plugin/issues/177
https://github.com/ktoso/maven-git-commit-id-plugin/issues/159
https://github.com/ktoso/maven-git-commit-id-plugin/issues/108
and was fixed with
https://github.com/ktoso/maven-git-commit-id-plugin/pull/157

I somehow agree that it breaks plugins backward compatibility but overwriting properties that the plugin is not supposed to overwrite is a no go.
However, this should be added to the readme (as already discussed in the other issues).

**Comment by TheSnoozer** [comment] 2015-04-13 14:01
Hi,
the ``<injectAllReactorProjects>``-Property was added to the README  (PR #187).
I also outline why we need to set it to false and therefore somehow break backwards compatibility.

If you feel that your issue is not yet resolved, please reopen the issue and share your concerns.

Thanks for reporting.

**Closed by TheSnoozer** 2015-04-13 14:01 UTC
Labels: docs
