### ISSUE TITLE
multi-module config with pluginManagement 

### ISSUE THREAD

**Issue by if6was9** [ktoso/maven-git-commit-id-plugin#81] opened 2013-11-16 15:13 UTC
Somewhere between 2.1.4 and now the behavior of the plugin has changed with regard to multi-module configuration.

Specifically, if the git-commit-id-plugin is configured in a <pluginManagement> section of a parent POM, the value of <generateGitPropertiesFilename> is now expanded with respect to the parent pom.

So even though the plugin may run multiple times in multiple maven submodules, it will overwrite the same file repeatedly.

In 2.1.4, the behavior was different.  If <generatedPropertiesFilename> was set to resources/git.properties in the parent pom, then it would be generated for each maven module:

```
submodule1/resources/git.properties
submodule2/resources/git.properties
```

**Comment by TheSnoozer** [comment] 2017-07-17 09:27
Even though this issue is already open for quite some time I did some debugging (https://github.com/TheSnoozer/git-commit-id-debugging)

Project structure:
- Parent-pom with maven-antrun-plugin that echo's the properties ${user.dir}, ${basedir} and ${project.basedir}
- submodule-one that inherits parent without any additional settings
- submodule-two that inherits parent without any additional settings

Output (mvn clean package):
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Git Commit Id Plugin Maven Mojo Debugging 0.0.1 (Parent)
[INFO] ------------------------------------------------------------------------
     [echo] user.dir: ~/workspace/git-commit-id-debugging
     [echo] basedir: ~/workspace/git-commit-id-debugging
     [echo] project.basedir: ~/workspace/git-commit-id-debugging

[INFO] ------------------------------------------------------------------------
[INFO] Building submodule-one 0.0.1
[INFO] ------------------------------------------------------------------------
     [echo] user.dir: ~/workspace/git-commit-id-debugging
     [echo] basedir: ~/workspace/git-commit-id-debugging/submodule-one
     [echo] project.basedir: ~/workspace/git-commit-id-debugging/submodule-one

[INFO] ------------------------------------------------------------------------
[INFO] Building submodule-two 0.0.1
[INFO] ------------------------------------------------------------------------
     [echo] user.dir: ~/workspace/git-commit-id-debugging
     [echo] basedir: ~/workspace/git-commit-id-debugging/submodule-two
     [echo] project.basedir: ~/workspace/git-commit-id-debugging/submodule-two
```

Didn't find any documents / manuals but with native maven without having the git-commit-id-mojo involved the property basedir and project.basedir are relative to the current pom (which makes a lot of sense) and user.dir always seems to point to the current execution path....

~ Closing as Not a Bug ~

**Closed by TheSnoozer** 2017-07-17 09:27 UTC
Labels: bug, testing
